### ISSUE TITLE
Repository folders as relative paths to portal

### ISSUE THREAD

**Issue by juvander** [DNNCommunity/DNN.Repository#24]
Already some time ago I implemented this into previous version so that especially move to Azure wold be a lot smoother without need to add fixed folders with hard paths to pending, anonymous & repository folders.

Any chance to get this into the version 4 as well? Could then start testing with that.

Changes were basically these two:
https://github.com/juvander/dnnrepository/commit/940a12070dc37236d7e9926d4fe16371a3aaa0ea
https://github.com/juvander/dnnrepository/commit/cfcc3db578361155565257b9008033ddc3622b99

**Comment by valadas** [comment]
Would'nt this prevent users from selecting other folders as destinations? I do not understand the goal and the relation to Azure move, can you elaborate on the issue?

**Comment by juvander** [comment]
For sure will prevent that, but why would you choose folder from other location? Playing with folders not under IIS website root will cause lots of configuration with permissions.
On Azure this is even worse since you cannot set all these permissions so you are stuck with the website where you installed your app. And you need to dig a bit deeper for even to find the path like c:\iis\website\appA
Much easier to just use relative path and let IIS take care of the rest.

**Comment by valadas** [comment]
Ok, just had time to check this. Yes you are correct that the full path should not be used, it should be relative to the application path. Can you submit a pull request based on current code?

**Comment by valadas** [comment]
Also @juvander is there really a need to make these fields readonly?

**Comment by juvander** [comment]
Readonly is just for users to see what the folder is but not able to change the value.

**Comment by gncube** [comment]
Hi @juvander could you make it possible to configure the repository folder to be an Azure Blog hosted folder.

**Comment by juvander** [comment]
For this you would need file system provider for DNN, not just how to configure repository as it is simply using that

**Comment by valadas** [comment]
PR merged
