### ISSUE TITLE
Breaking change to [URLCONTROLFILE] used on Repository Skin

### ISSUE THREAD

**Issue by gncube** [DNNCommunity/DNN.Repository#26]
## Description of the bug
After successfully upgrading from DNN9.1.0 to DNN9.2.0 a page with the repository module works fine to display and view the resources in the repository. On clicking the **Upload button** the error messages is displayed.

## Software Versions
- DNN: 09.02.00
- Module: 04.00.00

## To Reproduce
1. Go to 'repository page'
2. Click on 'Upload button'
3. See error **Object reference not set to an instance of an object.**

## Expected behavior
The DNN **/ctl/userupload/mid/416** page should be displayed with a form that uses the [URLCONTROLFILE] to chose the link type to the file needed to be uploaded or URL using the standard DNN [URLCONTROLFILE]. 

This bug is only presenting with the Repository Skin is using the [URLCONTROLFILE] instead of the common [FILE] attribute. 

## Screenshots

![image](https://user-images.githubusercontent.com/4821668/43432665-f0532796-946b-11e8-8f83-ab9c78db2b41.png) 

The page working in DNN9.1.0

![image](https://user-images.githubusercontent.com/4821668/43432689-0de89eda-946c-11e8-8825-3153a23d18e2.png)

Error showing in DNN9.2.0

## Error log
The error is not showing on the **Admin Logs**

## Additional context
The [URLCONTROLFILE] is needed to harness the use of **Azure Folder** the repository root folder.

## Repository Skin Form 
```
<table class="normal"  cellspacing="0" cellpadding="4">
	<tr height="40">
		<td class="Head" valign="top">[LABEL:Header]</td>
	</tr>
	<tr>
		<td class="normal" valign="top">[LABEL:NoModerationRequired][LABEL:ModerationRequired]<br />
			<br />
		</td>
	</tr>
	<tr>
		<td class="normal">
			<table class="SubHead" width="100%" cellspacing="0" cellpadding="0">
			<tr style="padding-bottom: 8px;">
					<td align="left" valign="top" width="150">[DNNLABEL:Categories]</td>
					<td align="left" valign="top">[CATEGORIES]</td>
				</tr>
				<tr style="padding-bottom: 8px;">
					<td align="left" valign="top" width="150">[DNNLabel:ATTRIBUTES]</td>
					<td align="left" valign="top">[ATTRIBUTES]</td>
				</tr>
				<tr style="padding-bottom: 8px;">
					<td align="left" valign="top" width="150">[DNNLABEL:Title]</td>
					<td align="left" valign="top">[TITLE]</td>
				</tr>
				<tr style="padding-bottom: 8px;">
					<td align="left" valign="top" width="150">[DNNLABEL:FileName]</td>
					<td align="left" valign="top">[URLCONTROLFILE]</td>
				</tr>				
			</table>
			<br />

		</td>
	</tr>
</table>
<div class="row">
				<div class="col-xs-12">
					
						[DNNLABEL:Description]<br />
						[DESCRIPTION]

				</div>
			</div>
			
	<div class="row">
				<div class="col-xs-12">					
			[LABEL:Guidelines]<br />
			[UPLOADBUTTON]&nbsp;[CANCELBUTTON]&nbsp;[DELETEBUTTON]<br />
	</div>
			</div>
```

**Comment by valadas** [comment]
Merged
