### ISSUE TITLE
Is there a current version?

### ISSUE THREAD

**Issue by jncraig** [DNNCommunity/DNN.Repository#34]
## Please summarize your question in one sentence

This question was asked on the Community Forum:  https://dnncommunity.org/forums/aft/701

**Comment by valadas** [comment]
The module releases are here https://github.com/DNNCommunity/DNN.Repository/releases latest release is 4.0.0 that was tested working on Dnn 9.2.x, there was 2 reported issues which I had no time to test/verify yet since I do not actively use this module.
