### ISSUE TITLE
When is the next version of the Repository module due to be released?

### ISSUE THREAD

**Issue by barnsley7** [DNNCommunity/DNN.Repository#35]
**##Q.**
When is the next version of the Repository module due to be released?

**##Summary**
The Latest Repository module (v4.0 at time of writing) claims to be tested in up to version 9.2 of  DNN. Is the Repository module still supported?
Are there any plans to get this working in future DNN versions? (as DNN 9.2 was released quite a while ago in Oct 2018).

Has anyone tested version 4.0 of the Repository module in later versions of DNN beyond 9.2?

thanks.

## Steps to reproduce (if needed)
I tried v4.0 with DNN 9.3 and it didn't work. Maybe it didn't work because of the order i tried things...? I initially had Repository v3.5.6 with DNN 9.1 which worked, then I upgraded DNN to 9.3 before upgrading the Repository to v4.0

## Other comments or remarks
So I was wondering if anyone has had any better luck with any DNN versions beyond 9.2?

**Comment by valadas** [comment]
There are no official release dates and no official maintainer for this module, we work on those as time permits, it was tested up to 9.2 but could work or not past it. I gonna close this issue, if you have problems please open a detailed issue with clear steps to reproduce and as much info as you can like logs in the browser console, in the admin logs and in the /Portals/_default/logs folder.

Unfortunately I do not use this module, I know @juvander has submitted many pull requests for it, would you like to get together to review/merge those, some have more commits than what they should, we could look into those together if you want and get a new release out?

**Comment by juvander** [comment]
I do have this running with 9.4.4 so should be fine in your case as well. BUT, I'm running my own version which includes those pull requests that have not been merged into this one.

**Comment by valadas** [comment]
@juvander would you like to get together and merge those, then make you the official maintainer of this one ? I can help you out

**Comment by juvander** [comment]
Sure

**Comment by valadas** [comment]
Cool, I pinged you up in Slack, we can get together and sort this out.

**Comment by juvander** [comment]
Not really active in there, but lets see if I can get in...

**Comment by valadas** [comment]
There you go @barnsley7 https://github.com/DNNCommunity/DNN.Repository/releases/tag/v4.1.0

**Comment by barnsley7** [comment]
ooh fantastic, i shall try this shortly 
thank you.
