### ISSUE TITLE
show my email address - in Repository Module

### ISSUE THREAD

**Issue by barnsley7** [DNNCommunity/DNN.Repository#36]
## Please summarize your question in one sentence
"_Show my email address_" - in Repository Module doesn't actually show my email address in the list

## Give a more extended description
in the Repository module there is a field to display the author's email address and a checkbox which says: "_show my email address_". My email address is shown in the form, but not displayed in the actual repository list.

Whether or not, I check this box - my email address or any other user's email address are ever shown in the Repository list.

I've tried several different templates and can see that the label which displays the email address in the 'form.html' file is [AUTHOREMAIL].

I've opened the 'template.html' file and the label/field [AUTHOREMAIL] is there, but it fails to display email addresses in the Repository list. It's just blank.

## Steps to reproduce (if needed)
1. create a Repository module,
2. Select any of the following repository templates: Default, Nifty, Metro, Articles, Directory
3. Create a new Repository item,
4. Enter an email address in the email field and tick the box: '_show my email address_'
5. Does the email address show in the Repository list (to end users)? - for me - it does not show here. (It only shows in the actual form when you edit the item).

## Other comments or remarks
Tested in Repository version 3.5.6 and v4.0
Tested in DNN versions: 7.4.2 , 8.0.4 , 9.1.1 and 9.2.2 
(same results in all versions)

**Comment by juvander** [comment]
Fix included in above pull request. No clue what was behind that if clause... was in the original vb code as well so I guess this has never worked...

**Comment by valadas** [comment]
PR Merged
