### ISSUE TITLE
repository not working properly in Chrome with filelist skin(works in all other browsers)

### ISSUE THREAD

**Issue by jverdes** [DNNCommunity/DNN.Repository#47]
## Describe the bug
repository not working properly in Chrome with filelist skin(works in all other browsers)
the dashboard works
the repository list objects change on dashboard selection but the downloadable files associated with an object will not change.  The downloadable files seem always stay the same as the initial page load. 

## Software Versions
- DNN: 9.6.1 and 9.3.2
- Module: 4.0 and 4.1

## To Reproduce
1. Go to https://das.ohio.gov/Divisions/General-Services/Asset-Management-Services/Certification/2020-Certification-Reports
2. Click on any one of the reports
3. Scroll down to repository and select download link for one of the reports

## Expected behavior
download link should match report

## Screenshots
![image](https://user-images.githubusercontent.com/21041441/94030117-75fcba80-fd8b-11ea-9992-b625dba6c634.png)

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

**Comment by juvander** [comment]
That is another weird one. Check how your cache settings are on module and on this page level.

**Comment by jverdes** [comment]
This is what our web team has found

It appears Chrome got more strict on SameSite cookie settings.
What I see different from older Chrome versions and the latest Edge is that they still allow a cookie to have a “SameSite” setting without a “Secure” setting.
Even though it does not appear to be necessary in this app, it sets a “_DRMCategory5686” cookie with “SameSite” but without “Secure”.
I see that value being updated to “1356” in working browsers but in the latest Chrome versions, it gets set to “-1” most likely because they no longer support that combo.
I don’t see that effect documented anywhere although I can always get it to play out as such.
You can even use the developer mode in the latest Chrome and manually change “-1” to “1356” and it will work for that session.

**Comment by juvander** [comment]
Ok, managed to replicate this, but removing the cookie did not do the trick. Cookie is used to store sorting order so it is indeed needed.
Will need to dig deeper into this.
Affects all skins, not just file list skin.

**Comment by juvander** [comment]
See how it works with this: https://1drv.ms/u/s!AtepqpoJ-cEfkawrX-1EkQ1bKBRwFA?e=PoRJGf

**Comment by juvander** [comment]
Fix now in release 4.1.1
