### ISSUE TITLE
error BC30469: Reference to a non-shared member requires an object reference.

### ISSUE THREAD

**Issue by barnsley7** [DNNCommunity/DNN.Repository#49]
## Please summarize your question in one sentence
 error BC30469: Reference to a non-shared member requires an object reference.

## Give a more extended description
just upgraded from dnn 7.4.2 to 8.0.4.
got this error on repository:
Error: Repository is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: C:\inetpub\wwwroot\JAGUWebsite\DesktopModules\Repository\Repository.ascx(2): error BC30469: Reference to a non-shared member requires an object reference. 

it was originally repository version 3.5.6, but upgraded to repository v4.0 then 4.1 to no avail (still same error above).
i uninstalled repository module
and installed version 4.0 again, but still get same error when adding new module to a page.

## Steps to reproduce (if needed)
uninstall repository module - install brand new repository module version 4.0

**Comment by juvander** [comment]
Best guess: Too old DNN version... I believe I once had a working version for 8.0.4, but long gone already and was not brought to this repository...

**Comment by barnsley7** [comment]
thanks, i'm going to upgrade to dnn 9 and see if that helps

**Comment by juvander** [comment]
Yes, I found the old vb version on my private repository, but there was a complete rewrite in C# and that in that DNN9 version is used on build.
