### ISSUE TITLE
Error adding dashboard module to page

### ISSUE THREAD

**Issue by trapias** [DNNCommunity/DNN.Repository#51]
## Describe the bug
Hello, I'm getting an error as soon as I add a repository dashboard module to the same page where I just configured a new repository module.
Modules do not show up on page, and in the log I find the error:

`InnerMessage:Riferimento a un oggetto non impostato su un'istanza di oggetto.
InnerStackTrace:
   in DotNetNuke.Modules.Repository.Helpers.SetRepositoryFolders(Int32 ModuleId)
   in DotNetNuke.Modules.Repository.RepositoryDashboard.Page_Load(Object sender, EventArgs e)
   in System.Web.UI.Control.OnLoad(EventArgs e)
   in DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Control.LoadRecursive()
   in System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

## Software Versions
- DNN: 9.7.2
- Module: 4.1.0

## To Reproduce
1. Add a new repository module to a blank page, configure it
2. Add a new repository dashboard module to the same page

## Expected behavior
Modules show on page.

## Additional context
The DNN site is new and has content localization enabled. I get the error both if I localize the page and if I set it to neutral language.

**Comment by albertovelo** [comment]
@valadas thanks, I managed to update the module myself just to keep it running until we find another solution.
You can close this issue.

Thanks,
al.

**Comment by valadas** [comment]
@albertovelo  Can you share your fix ?

**Comment by stetard** [comment]
I tested it with DNN 10.0.1 and the problem still exists.
@valadas Could you please reopen this issue? I would like to fix this.

**Comment by valadas** [comment]
Awesome, reopened and let me know when you feel a release is ready to produce.

**Comment by valadas** [comment]
@trapias and @stetard can you give a quick test to https://github.com/DNNCommunity/DNN.Repository/releases/tag/v4.2.0-beta.1 and let me know if you feel that is good to release. Thanks.

**Comment by stetard** [comment]
Hello @valadas 
It seems that there is at least another bug relative to the interactions between the dashboard module and the main module.

**Comment by albertovelo** [comment]
@valadas sorry I am unable to test right now, hopefully will try within this week
