### ISSUE TITLE
Files downloaded have extra data appended to the end of them

### ISSUE THREAD

**Issue by cdg191** [DNNCommunity/DNN.Repository#55]
## Describe the bug
Downloading a file with append extra data pertaining to the website to the end of the file.

## Software Versions
- DNN: 09.11.02
- Module: 04.01.00

## To Reproduce
Upload a file that is X bytes long.
Verify the file is still X bytes long in the DNN file system.
Download the file from the public facing UI.  The file is larger, sometimes significantly larger, than the original file.
If you examine the file, you'll see there is data appended to the end of the file, looking like it's from the website itself.

## Expected behavior
The download should be identical to the upload.

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

## Additional context
I intend to submit a pull request for it.  The problem is in StreamFile in Helper.cs

**Comment by maduranga001** [comment]
I am having the same issue. Please, can you help me with this? How we can fix this? if there is a file to download and replace, please, can I know the process?
