### ISSUE TITLE
Error when adding attributes 

### ISSUE THREAD

**Issue by innovation2solution** [DNNCommunity/DNN.Repository#70]
## Describe the bug
When logging in as either admin or host user I am unable to add any attribute or value. It just hangs and nothing happens.
Each time I try to add a new entry nothing happens. 
Is anyone else having this issue?

The workaround currently is to add entries in the DB but it means I have to do this and my users cannot. 

![image](https://github.com/DNNCommunity/DNN.Repository/assets/95965900/42127817-0465-45a3-97a8-5816fadf8cc1)

## Software Versions
- DNN: 09.13.03 
- Module: 4.1.2

## Expected behaviour
Typically I’d expect the attribute / value to be added to the list but instead when you click “add attribute” or "add value" nothing happens. 

## Screenshots
Above.

**Comment by innovation2solution** [comment]
Anyone else suffering this issue with v4.1.2?

Any ideas how to solve? I've tried in multiple browsers edge, safari and chrome but none seem to work...

**Comment by valadas** [comment]
I do not use this module but if anyone wants to sponsor a fix, I am willing to take a deeper look.

**Comment by innovation2solution** [comment]
Thank you. What does sponsor a fix mean please?
Apols first issue I've raised on DNN community.

**Comment by valadas** [comment]
@innovation2solution in general on the home page of a repository, you will see a list of contributors like this:
![image](https://github.com/DNNCommunity/DNN.Repository/assets/6371568/07d279f0-f67d-4bb1-9f69-207ab39f5f62)

Those are people the at one point or another have contributed to this repository. Clicking the "Contributors" title will bring you to a page with even more details to have a clue about who did most or more recently.
![image](https://github.com/DNNCommunity/DNN.Repository/assets/6371568/74f05700-f9b1-40a9-afa9-711c8ce71148)

Clicking on a user brings you to that user page like mine for instance:
![image](https://github.com/DNNCommunity/DNN.Repository/assets/6371568/b61c494c-c69f-43e3-ad9a-fa9374af0298)

And if that person accepts sponsorships, there will be a button under the picture that brings you to that user sponsorship page.
Everyone sets that up differently but in my case I take both monthly or one-time sponsorships.

https://github.com/sponsors/valadas?frequency=one-time

I believe that fixing this issue and producing a new release probably falls in my 1-2 hours work ones.

**Comment by innovation2solution** [comment]
Thank you. I've now submitted the sponsorship. Thank you for your support and help @valadas !

**Comment by valadas** [comment]
Thak YOU. I'll try to work on this late tonight.

**Comment by innovation2solution** [comment]
Hi @valadas 

Thanks for working on this.

Is there a new version I can use or do I just install the new version over the top?

How do I use and load in the fix?

thanks

**Comment by innovation2solution** [comment]
Do I just download and replace the file : Settings.ascx.cs and that’ll work?

**Comment by valadas** [comment]
I was looking if there was other low hanging fruits here to bundle together with the next release but what is left is kind of a big ticket item for updates.

I just published a new release here you can download and install using DNN. I would recommend just to backup before just in case.

https://github.com/DNNCommunity/DNN.Repository/releases/tag/v4.1.3

Thanks for your sponsorship and let me know how testing goes.

**Comment by innovation2solution** [comment]
Arh understood.

Awesome, thank you so much for helping out and turning this around so quick.

I'll drop into UAT and let you know how it goes 👍

**Comment by innovation2solution** [comment]
Hi @valadas 

Good news and bad news.

I've installed and tested the new module. The "add attribute" works perfectly (thank you) BUT the "add value" isn't as slick, it's hit and miss as to whether it'll work (similar issue to adding the attribute). 

Also when i load the module and update it still has the "admin" label i have to add a break in the  WYSIWYG editor or add test to clear this. Just by saving the settings i was hoping this would remove the "admin" tag,  you need to add content to this for it to remove the "admin" label when first installing or making any changes to the module. If you remove any text from the WSIWYG you get the "Admin" notice on the module. 

I can live with the WSIWYG as i know that's a new bug but the value one is going to give me headaches.

Thanks as always for your help and support,
Si

**Comment by valadas** [comment]
Thanks for the quick turnaround on testing.

I'll look at the attribute one soonish.

I am not understanding what you mean about the "Admin" part, can you create a new issue with potentially a screenshot or some such for the admin tag you are talking about.

**Comment by innovation2solution** [comment]
Thanks and sure, will do :)

**Comment by valadas** [comment]
@innovation2solution you can give https://github.com/DNNCommunity/DNN.Repository/releases/tag/v4.1.4 a try now and do open new issues if you find something not right... Thanks.
