### ISSUE TITLE
Error when adding attribute values

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.Repository#75]
## Describe the bug
In #70 a fix was done for attributes but the same problem happens with attribute values

I'll submit a PR to fix this shortly.

**Comment by innovation2solution** [comment]
Hi @valadas 

Thanks so much for this. I've reviewed the latest version in our test environment and can confirm this bug is resolved!

Awesome, thanks again much appreciated!

**Comment by valadas** [comment]
Awesome, thanks for sponsoring this fix!
